### ISSUE TITLE
What to do if i want to accept command line arguments for my entry point?

### ISSUE THREAD

**Issue by abtpst** [idlerun/simple-pex#1]
What to do if i want to accept command line arguments for my entry point?

**Comment by idlerun** [comment]
It should just work as normal for Python arguments (pex doesn't need any changes)

We can modify the sample code to output arguments:

`main.py`

```python
import requests
import sys
print("HELLO WORLD!! args={0}".format(sys.argv))
```

And check with

```bash
./samplepkg.pex hello world
HELLO WORLD!! args=['./samplepkg.pex', 'hello', 'world']
```

For handling command line configuration flags I'd recommend using something like [argparse](https://docs.python.org/3/howto/argparse.html)
